### ISSUE TITLE
Side notes

### ISSUE THREAD

**Issue by NouraldinS** [FACG6/Posts-Handlebars#24]
You should remove all console logs before deployment.
Yes you probably haven't had the time to do any HTML or CSS, but you could've at least painted the background, added a few margins or paddings, the style requirement isn't that high, but at least there should be some styles implemented.

@ahmedisam99 @AymanAlqoqa @alaabadra Good effort, I know it's been hard getting into Express and handlebars at the same time, but you did well.

There is a reading week in the next 3 weeks (I really don't remember when exactly), you should take that time and revise the past 8 weeks well, it'll be a very good practice.

**Comment by alaabadra** [comment]
Thank you noureldean ☺
 we done the style of our project ,but we have'nt the time to push this style here

**Comment by NouraldinS** [comment]
@alaabadra Its ok the style isn't that hard to learn anyway, the most important thing is that you all have the best understanding of the components around your code such as routers, controllers, middlewares, queries,... etc.

**Comment by alaabadra** [comment]
Exactly ☺
Thank you
